/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "F:\\blacklisten\\vuepressblogs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-12da3b52",
    path: "/About.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-12da3b52").then(next)
    },
  },
  {
    name: "v-699c6f32",
    path: "/views/2020/Chocolatey.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-699c6f32").then(next)
    },
  },
  {
    name: "v-78d5e149",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-78d5e149").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-7bd064d2",
    path: "/views/2020/ChromeConfig.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7bd064d2").then(next)
    },
  },
  {
    name: "v-2d87369c",
    path: "/views/2020/Electron-win7-black-screen.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d87369c").then(next)
    },
  },
  {
    name: "v-482ff771",
    path: "/views/2020/Electron%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-482ff771").then(next)
    },
  },
  {
    path: "/views/2020/Electron学习笔记.html",
    redirect: "/views/2020/Electron%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0.html"
  },
  {
    name: "v-561cc7e6",
    path: "/views/2020/Front.specification.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-561cc7e6").then(next)
    },
  },
  {
    name: "v-3bf3fd5c",
    path: "/views/2020/WindowTerminal.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3bf3fd5c").then(next)
    },
  },
  {
    name: "v-e6140b9c",
    path: "/views/2020/TypeScript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e6140b9c").then(next)
    },
  },
  {
    name: "v-798073da",
    path: "/views/2020/gitignore.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-798073da").then(next)
    },
  },
  {
    name: "v-6519c5a6",
    path: "/views/2020/koabodyparser.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6519c5a6").then(next)
    },
  },
  {
    name: "v-784fb80c",
    path: "/views/2020/win%E4%B8%8Bvscode%E8%BF%90%E8%A1%8Cbash%E7%BB%88%E7%AB%AF.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-784fb80c").then(next)
    },
  },
  {
    path: "/views/2020/win下vscode运行bash终端.html",
    redirect: "/views/2020/win%E4%B8%8Bvscode%E8%BF%90%E8%A1%8Cbash%E7%BB%88%E7%AB%AF.html"
  },
  {
    name: "v-2734862c",
    path: "/views/2020/learnDartLanguage.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2734862c").then(next)
    },
  },
  {
    name: "v-56715e63",
    path: "/views/2020/%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85%E5%A4%9A%E4%B8%AA%E7%89%88%E6%9C%AC%E7%9A%84node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-56715e63").then(next)
    },
  },
  {
    path: "/views/2020/如何安装多个版本的node.html",
    redirect: "/views/2020/%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85%E5%A4%9A%E4%B8%AA%E7%89%88%E6%9C%AC%E7%9A%84node.html"
  },
  {
    name: "v-04d26464",
    path: "/views/2020/%E5%A6%82%E4%BD%95%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%87%E6%8D%A2node%E6%BA%90.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04d26464").then(next)
    },
  },
  {
    path: "/views/2020/如何自定义切换node源.html",
    redirect: "/views/2020/%E5%A6%82%E4%BD%95%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%87%E6%8D%A2node%E6%BA%90.html"
  },
  {
    name: "v-598e59ba",
    path: "/views/previous/Array.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-598e59ba").then(next)
    },
  },
  {
    name: "v-3244ecdc",
    path: "/views/previous/ShadowSocks%E9%85%8D%E7%BD%AE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3244ecdc").then(next)
    },
  },
  {
    path: "/views/previous/ShadowSocks配置.html",
    redirect: "/views/previous/ShadowSocks%E9%85%8D%E7%BD%AE.html"
  },
  {
    name: "v-43b64ffd",
    path: "/views/previous/JavaScript%E7%BB%A7%E6%89%BF%E7%9A%84%E5%A4%9A%E7%A7%8D%E6%96%B9%E5%BC%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-43b64ffd").then(next)
    },
  },
  {
    path: "/views/previous/JavaScript继承的多种方式.html",
    redirect: "/views/previous/JavaScript%E7%BB%A7%E6%89%BF%E7%9A%84%E5%A4%9A%E7%A7%8D%E6%96%B9%E5%BC%8F.html"
  },
  {
    name: "v-1b25e39c",
    path: "/views/previous/This.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b25e39c").then(next)
    },
  },
  {
    name: "v-5ce495d4",
    path: "/views/previous/addRoutes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ce495d4").then(next)
    },
  },
  {
    name: "v-4dc17d40",
    path: "/views/previous/arguments.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4dc17d40").then(next)
    },
  },
  {
    name: "v-59ebb44b",
    path: "/views/previous/Flex%E5%B8%83%E5%B1%80.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59ebb44b").then(next)
    },
  },
  {
    path: "/views/previous/Flex布局.html",
    redirect: "/views/previous/Flex%E5%B8%83%E5%B1%80.html"
  },
  {
    name: "v-4216b42a",
    path: "/views/previous/call%E3%80%81apply%E7%9A%84%E6%A8%A1%E6%8B%9F%E5%AE%9E%E7%8E%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4216b42a").then(next)
    },
  },
  {
    path: "/views/previous/call、apply的模拟实现.html",
    redirect: "/views/previous/call%E3%80%81apply%E7%9A%84%E6%A8%A1%E6%8B%9F%E5%AE%9E%E7%8E%B0.html"
  },
  {
    name: "v-d7d57520",
    path: "/views/previous/eventloop.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d7d57520").then(next)
    },
  },
  {
    name: "v-8c46bd88",
    path: "/views/previous/gitalk%E6%90%AD%E5%BB%BA%E9%81%87%E8%A7%81%E7%9A%84%E9%97%AE%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8c46bd88").then(next)
    },
  },
  {
    path: "/views/previous/gitalk搭建遇见的问题.html",
    redirect: "/views/previous/gitalk%E6%90%AD%E5%BB%BA%E9%81%87%E8%A7%81%E7%9A%84%E9%97%AE%E9%A2%98.html"
  },
  {
    name: "v-12f54de6",
    path: "/views/previous/git%20Please%20move%20or%20remove%20them%20before%20you%20can%20merge.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-12f54de6").then(next)
    },
  },
  {
    path: "/views/previous/git Please move or remove them before you can merge.html",
    redirect: "/views/previous/git%20Please%20move%20or%20remove%20them%20before%20you%20can%20merge.html"
  },
  {
    name: "v-4f10c5cf",
    path: "/views/previous/jQuery%20is%20not%20defind.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f10c5cf").then(next)
    },
  },
  {
    path: "/views/previous/jQuery is not defind.html",
    redirect: "/views/previous/jQuery%20is%20not%20defind.html"
  },
  {
    name: "v-1a64f484",
    path: "/views/previous/hexo-next%E4%B8%BB%E9%A2%98%E9%9B%86%E6%88%90gitalk%E8%AF%84%E8%AE%BA%E6%8F%92%E4%BB%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1a64f484").then(next)
    },
  },
  {
    path: "/views/previous/hexo-next主题集成gitalk评论插件.html",
    redirect: "/views/previous/hexo-next%E4%B8%BB%E9%A2%98%E9%9B%86%E6%88%90gitalk%E8%AF%84%E8%AE%BA%E6%8F%92%E4%BB%B6.html"
  },
  {
    name: "v-59f43e67",
    path: "/views/previous/markdown%E8%AF%AD%E6%B3%95%E7%AE%80%E4%BB%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59f43e67").then(next)
    },
  },
  {
    path: "/views/previous/markdown语法简介.html",
    redirect: "/views/previous/markdown%E8%AF%AD%E6%B3%95%E7%AE%80%E4%BB%8B.html"
  },
  {
    name: "v-005efac6",
    path: "/views/previous/nodejs%E5%86%99%E6%97%A5%E5%BF%97.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-005efac6").then(next)
    },
  },
  {
    path: "/views/previous/nodejs写日志.html",
    redirect: "/views/previous/nodejs%E5%86%99%E6%97%A5%E5%BF%97.html"
  },
  {
    name: "v-70e1cfd2",
    path: "/views/previous/registerModule.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70e1cfd2").then(next)
    },
  },
  {
    name: "v-10da82dc",
    path: "/views/previous/renderVModel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-10da82dc").then(next)
    },
  },
  {
    name: "v-636d1913",
    path: "/views/previous/vscode%E6%8F%92%E4%BB%B6%E7%AF%87.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-636d1913").then(next)
    },
  },
  {
    path: "/views/previous/vscode插件篇.html",
    redirect: "/views/previous/vscode%E6%8F%92%E4%BB%B6%E7%AF%87.html"
  },
  {
    name: "v-5370e5e4",
    path: "/views/previous/vue-communication.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5370e5e4").then(next)
    },
  },
  {
    name: "v-07995389",
    path: "/views/previous/%E5%8E%9F%E5%9E%8B%E5%92%8C%E5%8E%9F%E5%9E%8B%E9%93%BE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-07995389").then(next)
    },
  },
  {
    path: "/views/previous/原型和原型链.html",
    redirect: "/views/previous/%E5%8E%9F%E5%9E%8B%E5%92%8C%E5%8E%9F%E5%9E%8B%E9%93%BE.html"
  },
  {
    name: "v-e4ebfae8",
    path: "/views/previous/%E6%8E%A2%E7%B4%A2Vue%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e4ebfae8").then(next)
    },
  },
  {
    path: "/views/previous/探索Vue生命周期.html",
    redirect: "/views/previous/%E6%8E%A2%E7%B4%A2Vue%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F.html"
  },
  {
    name: "v-070152e4",
    path: "/views/previous/%E6%A8%A1%E5%9D%97%E8%A7%84%E8%8C%83.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-070152e4").then(next)
    },
  },
  {
    path: "/views/previous/模块规范.html",
    redirect: "/views/previous/%E6%A8%A1%E5%9D%97%E8%A7%84%E8%8C%83.html"
  },
  {
    name: "v-c5d3e760",
    path: "/views/previous/%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c5d3e760").then(next)
    },
  },
  {
    path: "/views/previous/正则表达式.html",
    redirect: "/views/previous/%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F.html"
  },
  {
    name: "v-3a7d39ab",
    path: "/views/previous/%E6%B7%B1%E7%A9%B6JavaScript%E5%80%BC%E4%BC%A0%E9%80%92%E5%92%8C%E5%BC%95%E7%94%A8%E4%BC%A0%E9%80%92.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a7d39ab").then(next)
    },
  },
  {
    path: "/views/previous/深究JavaScript值传递和引用传递.html",
    redirect: "/views/previous/%E6%B7%B1%E7%A9%B6JavaScript%E5%80%BC%E4%BC%A0%E9%80%92%E5%92%8C%E5%BC%95%E7%94%A8%E4%BC%A0%E9%80%92.html"
  },
  {
    name: "v-09457a67",
    path: "/views/previous/%E7%90%86%E8%A7%A3async&await.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09457a67").then(next)
    },
  },
  {
    path: "/views/previous/理解async&await.html",
    redirect: "/views/previous/%E7%90%86%E8%A7%A3async&await.html"
  },
  {
    name: "v-7219b802",
    path: "/views/previous/%E8%8A%82%E6%B5%81%E9%98%B2%E6%8A%96.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7219b802").then(next)
    },
  },
  {
    path: "/views/previous/节流防抖.html",
    redirect: "/views/previous/%E8%8A%82%E6%B5%81%E9%98%B2%E6%8A%96.html"
  },
  {
    name: "v-a22f2220",
    path: "/views/previous/%E8%AF%8D%E6%B3%95%E4%BD%9C%E7%94%A8%E5%9F%9F%E3%80%81%E5%8A%A8%E6%80%81%E4%BD%9C%E7%94%A8%E5%9F%9F%E3%80%81%E5%8F%98%E9%87%8F%E6%8F%90%E5%8D%87.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a22f2220").then(next)
    },
  },
  {
    path: "/views/previous/词法作用域、动态作用域、变量提升.html",
    redirect: "/views/previous/%E8%AF%8D%E6%B3%95%E4%BD%9C%E7%94%A8%E5%9F%9F%E3%80%81%E5%8A%A8%E6%80%81%E4%BD%9C%E7%94%A8%E5%9F%9F%E3%80%81%E5%8F%98%E9%87%8F%E6%8F%90%E5%8D%87.html"
  },
  {
    name: "v-d2cd4c30",
    path: "/views/previous/%E8%B0%83%E7%94%A8%E5%A0%86%E6%A0%88.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d2cd4c30").then(next)
    },
  },
  {
    path: "/views/previous/调用堆栈.html",
    redirect: "/views/previous/%E8%B0%83%E7%94%A8%E5%A0%86%E6%A0%88.html"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-cd93ecc0",
    path: "/tag/杂谈/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-cd93ecc0").then(next)
    },
    meta: {"pid":"tags","id":"杂谈"}
  },
  {
    path: "/tag/杂谈/index.html",
    redirect: "/tag/杂谈/"
  },
  {
    path: "/tag/%E6%9D%82%E8%B0%88/",
    redirect: "/tag/杂谈/"
  },
  {
    name: "v-6bf1c8da",
    path: "/tag/nodejs/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-6bf1c8da").then(next)
    },
    meta: {"pid":"tags","id":"nodejs"}
  },
  {
    path: "/tag/nodejs/index.html",
    redirect: "/tag/nodejs/"
  },
  {
    name: "v-7213ab03",
    path: "/tag/Electron/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-7213ab03").then(next)
    },
    meta: {"pid":"tags","id":"Electron"}
  },
  {
    path: "/tag/Electron/index.html",
    redirect: "/tag/Electron/"
  },
  {
    name: "v-2d17ea9b",
    path: "/tag/日常错误问题收集/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-2d17ea9b").then(next)
    },
    meta: {"pid":"tags","id":"日常错误问题收集"}
  },
  {
    path: "/tag/日常错误问题收集/index.html",
    redirect: "/tag/日常错误问题收集/"
  },
  {
    path: "/tag/%E6%97%A5%E5%B8%B8%E9%94%99%E8%AF%AF%E9%97%AE%E9%A2%98%E6%94%B6%E9%9B%86/",
    redirect: "/tag/日常错误问题收集/"
  },
  {
    name: "v-5f66a358",
    path: "/tag/javaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-5f66a358").then(next)
    },
    meta: {"pid":"tags","id":"javaScript"}
  },
  {
    path: "/tag/javaScript/index.html",
    redirect: "/tag/javaScript/"
  },
  {
    name: "v-bee809c0",
    path: "/tag/TypeScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-bee809c0").then(next)
    },
    meta: {"pid":"tags","id":"TypeScript"}
  },
  {
    path: "/tag/TypeScript/index.html",
    redirect: "/tag/TypeScript/"
  },
  {
    name: "v-61ab3e8c",
    path: "/tag/Nodejs/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-61ab3e8c").then(next)
    },
    meta: {"pid":"tags","id":"Nodejs"}
  },
  {
    path: "/tag/Nodejs/index.html",
    redirect: "/tag/Nodejs/"
  },
  {
    name: "v-58d4c3a7",
    path: "/tag/编辑器/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-58d4c3a7").then(next)
    },
    meta: {"pid":"tags","id":"编辑器"}
  },
  {
    path: "/tag/编辑器/index.html",
    redirect: "/tag/编辑器/"
  },
  {
    path: "/tag/%E7%BC%96%E8%BE%91%E5%99%A8/",
    redirect: "/tag/编辑器/"
  },
  {
    name: "v-18b15ff4",
    path: "/tag/Dart/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-18b15ff4").then(next)
    },
    meta: {"pid":"tags","id":"Dart"}
  },
  {
    path: "/tag/Dart/index.html",
    redirect: "/tag/Dart/"
  },
  {
    name: "v-563fc05d",
    path: "/tag/Flutter/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-563fc05d").then(next)
    },
    meta: {"pid":"tags","id":"Flutter"}
  },
  {
    path: "/tag/Flutter/index.html",
    redirect: "/tag/Flutter/"
  },
  {
    name: "v-3257dcde",
    path: "/tag/ES6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3257dcde").then(next)
    },
    meta: {"pid":"tags","id":"ES6"}
  },
  {
    path: "/tag/ES6/index.html",
    redirect: "/tag/ES6/"
  },
  {
    name: "v-e14f25f6",
    path: "/tag/Linux/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e14f25f6").then(next)
    },
    meta: {"pid":"tags","id":"Linux"}
  },
  {
    path: "/tag/Linux/index.html",
    redirect: "/tag/Linux/"
  },
  {
    name: "v-32475d9a",
    path: "/tag/Vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-32475d9a").then(next)
    },
    meta: {"pid":"tags","id":"Vue"}
  },
  {
    path: "/tag/Vue/index.html",
    redirect: "/tag/Vue/"
  },
  {
    name: "v-3259a754",
    path: "/tag/CSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3259a754").then(next)
    },
    meta: {"pid":"tags","id":"CSS"}
  },
  {
    path: "/tag/CSS/index.html",
    redirect: "/tag/CSS/"
  },
  {
    name: "v-32555732",
    path: "/tag/Git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-32555732").then(next)
    },
    meta: {"pid":"tags","id":"Git"}
  },
  {
    path: "/tag/Git/index.html",
    redirect: "/tag/Git/"
  },
  {
    name: "v-644c5aac",
    path: "/categories/杂谈/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-644c5aac").then(next)
    },
    meta: {"pid":"categories","id":"杂谈"}
  },
  {
    path: "/categories/杂谈/index.html",
    redirect: "/categories/杂谈/"
  },
  {
    path: "/categories/%E6%9D%82%E8%B0%88/",
    redirect: "/categories/杂谈/"
  },
  {
    name: "v-dbc4c9e2",
    path: "/categories/Electron/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-dbc4c9e2").then(next)
    },
    meta: {"pid":"categories","id":"Electron"}
  },
  {
    path: "/categories/Electron/index.html",
    redirect: "/categories/Electron/"
  },
  {
    name: "v-0e7b8553",
    path: "/categories/Learning/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-0e7b8553").then(next)
    },
    meta: {"pid":"categories","id":"Learning"}
  },
  {
    path: "/categories/Learning/index.html",
    redirect: "/categories/Learning/"
  },
  {
    name: "v-7f008cdb",
    path: "/categories/Git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7f008cdb").then(next)
    },
    meta: {"pid":"categories","id":"Git"}
  },
  {
    path: "/categories/Git/index.html",
    redirect: "/categories/Git/"
  },
  {
    name: "v-466e3874",
    path: "/categories/Nodejs/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-466e3874").then(next)
    },
    meta: {"pid":"categories","id":"Nodejs"}
  },
  {
    path: "/categories/Nodejs/index.html",
    redirect: "/categories/Nodejs/"
  },
  {
    name: "v-33c9dede",
    path: "/categories/其它/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-33c9dede").then(next)
    },
    meta: {"pid":"categories","id":"其它"}
  },
  {
    path: "/categories/其它/index.html",
    redirect: "/categories/其它/"
  },
  {
    path: "/categories/%E5%85%B6%E5%AE%83/",
    redirect: "/categories/其它/"
  },
  {
    name: "v-14bbbf36",
    path: "/categories/前端/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-14bbbf36").then(next)
    },
    meta: {"pid":"categories","id":"前端"}
  },
  {
    path: "/categories/前端/index.html",
    redirect: "/categories/前端/"
  },
  {
    path: "/categories/%E5%89%8D%E7%AB%AF/",
    redirect: "/categories/前端/"
  },
  {
    name: "v-5f0beb54",
    path: "/categories/移动端/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-5f0beb54").then(next)
    },
    meta: {"pid":"categories","id":"移动端"}
  },
  {
    path: "/categories/移动端/index.html",
    redirect: "/categories/移动端/"
  },
  {
    path: "/categories/%E7%A7%BB%E5%8A%A8%E7%AB%AF/",
    redirect: "/categories/移动端/"
  },
  {
    name: "v-62e05b9d",
    path: "/categories/hexo/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-62e05b9d").then(next)
    },
    meta: {"pid":"categories","id":"hexo"}
  },
  {
    path: "/categories/hexo/index.html",
    redirect: "/categories/hexo/"
  },
  {
    name: "v-f2250136",
    path: "/tag/javaScript/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f2250136").then(next)
    },
    meta: {"pid":"tags","id":"javaScript"}
  },
  {
    path: "/tag/javaScript/page/2/index.html",
    redirect: "/tag/javaScript/page/2/"
  },
  {
    name: "v-260e2472",
    path: "/categories/前端/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-260e2472").then(next)
    },
    meta: {"pid":"categories","id":"前端"}
  },
  {
    path: "/categories/前端/page/2/index.html",
    redirect: "/categories/前端/page/2/"
  },
  {
    path: "/categories/%E5%89%8D%E7%AB%AF/page/2/",
    redirect: "/categories/前端/page/2/"
  },
  {
    name: "v-260e2434",
    path: "/categories/前端/page/3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-260e2434").then(next)
    },
    meta: {"pid":"categories","id":"前端"}
  },
  {
    path: "/categories/前端/page/3/index.html",
    redirect: "/categories/前端/page/3/"
  },
  {
    path: "/categories/%E5%89%8D%E7%AB%AF/page/3/",
    redirect: "/categories/前端/page/3/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]