/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Black_Chen'Blog",
  "description": "不能因理想遥远而放弃追求 不能因现实复杂而放弃梦想",
  "base": "/",
  "pages": [
    {
      "title": "About me",
      "frontmatter": {
        "title": "About me",
        "sidebar": false,
        "publish": false
      },
      "regularPath": "/About.html",
      "relativePath": "About.md",
      "key": "v-b8ec1006",
      "path": "/About.html",
      "lastUpdated": "2019-12-26 14:34:03"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "bgImage": "https://s2.ax1x.com/2019/07/03/ZNFR3j.png",
        "bgImageStyle": {
          "height": "350px"
        },
        "faceImage": "/avatar.jpg"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-7f43af84",
      "path": "/",
      "lastUpdated": "2019-12-26 14:34:03"
    },
    {
      "title": "Vue的几种通信方式",
      "frontmatter": {
        "title": "Vue的几种通信方式",
        "date": "2019-07-22T16:45:31.000Z",
        "tags": [
          "Vue"
        ],
        "categories": [
          "前端"
        ]
      },
      "regularPath": "/views/vue-communication.html",
      "relativePath": "views/vue-communication.md",
      "key": "v-4e942b50",
      "path": "/views/vue-communication.html",
      "headers": [
        {
          "level": 2,
          "title": "props / emit",
          "slug": "props-emit"
        },
        {
          "level": 2,
          "title": "vuex",
          "slug": "vuex"
        },
        {
          "level": 2,
          "title": "EventBus",
          "slug": "eventbus"
        },
        {
          "level": 2,
          "title": "$attrs / $listeners",
          "slug": "attrs-listeners"
        },
        {
          "level": 2,
          "title": "provide / inject",
          "slug": "provide-inject"
        },
        {
          "level": 2,
          "title": "不推荐系列",
          "slug": "不推荐系列"
        },
        {
          "level": 3,
          "title": "ref / refs",
          "slug": "ref-refs"
        },
        {
          "level": 3,
          "title": "$children / $parent",
          "slug": "children-parent"
        },
        {
          "level": 3,
          "title": "mixins",
          "slug": "mixins"
        },
        {
          "level": 3,
          "title": "Vue.prototype（这里只是举例子，原型的作用并不在于数据传递）",
          "slug": "vue-prototype（这里只是举例子，原型的作用并不在于数据传递）"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\">\n<p>Vue常用的几种通信传递</p>\n</div>\n",
      "lastUpdated": "2019-12-26 14:34:03"
    },
    {
      "title": "探索Vue生命周期",
      "frontmatter": {
        "title": "探索Vue生命周期",
        "date": "2019-02-22T18:55:47.000Z",
        "tags": [
          "Vue"
        ],
        "categories": [
          "前端"
        ]
      },
      "regularPath": "/views/%E6%8E%A2%E7%B4%A2Vue%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F.html",
      "relativePath": "views/探索Vue生命周期.md",
      "key": "v-c263b034",
      "path": "/views/%E6%8E%A2%E7%B4%A2Vue%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F.html",
      "excerpt": "<div class=\"custom-block tip\">\n<p>Vue生命周期探秘</p>\n</div>\n",
      "lastUpdated": "2019-12-26 14:34:03"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Vue tags"
      },
      "regularPath": "/tags/Vue/",
      "key": "v-6683f60a",
      "path": "/tags/Vue/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "前端 categories"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AF/",
      "key": "v-14bbbf36",
      "path": "/categories/前端/"
    }
  ],
  "themeConfig": {
    "type": "blog",
    "logo": "/avatar.jpg",
    "autoHideNavbar": true,
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "Category"
      },
      "tag": {
        "location": 3,
        "text": "Tag"
      }
    },
    "author": "blacklisten",
    "startYear": "2018",
    "nav": [
      {
        "text": "Home",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "TimeLine",
        "link": "/TimeLine/",
        "icon": "reco-date"
      },
      {
        "text": "About",
        "link": "/About.html",
        "icon": "reco-account"
      },
      {
        "text": "Contact",
        "icon": "reco-message",
        "items": [
          {
            "text": "Github",
            "link": "https://github.com/blacklisten",
            "icon": "reco-github"
          }
        ]
      }
    ],
    "friendLink": [],
    "sidebarDepth": 1,
    "sidebar": "auto",
    "vssueConfig": {
      "platform": "github",
      "owner": "blacklisten",
      "repo": "blacklisten.github.io",
      "clientId": "62731e14a44db4625efe",
      "clientSecret": "8d9dd74aa3d13f0fa7d8a20eaa225d425878e0e8"
    },
    "lastUpdated": "Last Updated",
    "docsRepo": "SigureMo/notev",
    "docsDir": "docs",
    "docsBranch": "master",
    "editLinks": true,
    "editLinkText": "在GitHub上编辑此页！",
    "serviceWorker": {
      "updatePopup": true
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}