/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "Vue": {
      "key": "Vue",
      "scope": "tags",
      "path": "/tags/Vue/",
      "pageKeys": [
        "v-6e0fafb6",
        "v-427cde8a"
      ]
    }
  },
  "categories": {
    "前端": {
      "key": "前端",
      "scope": "categories",
      "path": "/categories/前端/",
      "pageKeys": [
        "v-6e0fafb6",
        "v-427cde8a"
      ]
    }
  },
  "timeline": {}
}